# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: OmegaT.OmegaT
PackageVersion: 5.8.0
Installers:
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://sourceforge.net/projects/omegat/files/OmegaT%20-%20Latest/OmegaT%205.8.0/OmegaT_5.8.0_Beta_Windows_64_Signed.exe/download
  InstallerSha256: FA31E79AE29EA8FF17D0FFC263889CC712F7A74C596E4A9DBBC821BA4A6B6EB3
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://sourceforge.net/projects/omegat/files/OmegaT%20-%20Latest/OmegaT%205.8.0/OmegaT_5.8.0_Beta_Windows_Signed.exe/download
  InstallerSha256: 3164D6630431B0E2A0F706D94D513432FD8DF057CFC1B29D8586EDB774BD0603
ManifestType: installer
ManifestVersion: 1.2.0
